#!/usr/bin/env python3
"""Write TNT-equivalent charges (TntEquivalentKg) from the research table into the mod data.

Inputs
  --table      tnt_table.json: {"munitions": [{"key": ..., "tnt_kg": float, ...}],
                                "rows": {"<inventory row id>": "<munition key>" | null}}
  --inventory  munition_inventory.tsv (generated by make_inventory.py; column 'file' names the JSON file)

Targets (per inventory row id)
  <ns>:<vehicle>/<weapon>                       Weapons.<weapon>.TntEquivalentKg (vehicle JSON)
  <ns>:<vehicle>/<weapon>[AmmoType[i]]          Weapons.<weapon>.AmmoType[i].Override.TntEquivalentKg
  <ns>:<vehicle>/<weapon>[ProjectileBeltAmmoType[i]]  ...ProjectileBeltAmmoType[i].Override.TntEquivalentKg
  berts_vehicle_pack:guns/<path>                TntEquivalentKg (BVP gun profile)
  superbwarfare:<gun>[AmmoType[i]]              TntEquivalentKg / AmmoType[i].Override.TntEquivalentKg (SBW gun)
  berts_vehicle_pack:aircraft_stores/<path>     Bomb.TntEquivalentKg | Flight.TntEquivalentKg |
                                                LaunchGunProfile/GunProfile gun JSON | top-level (FFA store
                                                without a Flight block)
  ...#bomblet                                   Bomb.Cluster.BombletTntEquivalentKg
  superbwarfare:drone_attachment/<name>         TntEquivalentKg (drone attachment)
  rows whose file is .kt/.java                  sbw/.../data/superbwarfare/blast/tnt_defaults.json entries[row id]
  ...#destroy                                   skipped: vehicle death explosions stay on the legacy path

Semantics
  mapped to a munition with tnt_kg > 0   write the value
  mapped to null (or tnt_kg == 0)        remove the key; an AmmoType/belt override instead gets an explicit 0
                                         when its base weapon carries a charge (it would inherit it otherwise)
  not listed in "rows"                   base values unchanged (reported as unmapped); overrides are normalized
  AmmoType/belt entries with an Override but no inventory row (non-explosive ammo) of a charged base weapon
  are forced to 0; entries without an Override use the base weapon's values and keep its charge.

Edits are surgical (only the touched member changes, formatting is preserved), so the script is idempotent:
a second run reports no changes. Use --dry-run to print the plan without writing.
"""
import argparse
import json
import math
import os
import re
import sys
from collections import OrderedDict, defaultdict

KEY = "TntEquivalentKg"
BOMBLET_KEY = "BombletTntEquivalentKg"
MAX_KG = 100000.0
DEFAULTS_PATH = "sbw/src/main/resources/data/superbwarfare/blast/tnt_defaults.json"
BVP_GUNS = "bvp/src/generated/resources/data/berts_vehicle_pack/sbw/guns"
OVERRIDE_LISTS = ("AmmoType", "ProjectileBeltAmmoType")
ROW_SUFFIX = re.compile(r"^(?P<head>.*?)(?:\[(?P<list>AmmoType|ProjectileBeltAmmoType)\[(?P<index>\d+)\]\])?$")


# --------------------------------------------------------------------------------------------------------------
# Minimal span-tracking JSON parser: edits touch only the member they change.
# --------------------------------------------------------------------------------------------------------------
class Node:
    __slots__ = ("kind", "start", "end", "members", "items", "value")

    def __init__(self, kind, start):
        self.kind, self.start, self.end = kind, start, start
        self.members, self.items, self.value = [], [], None

    def member(self, key):
        for m in self.members:
            if m.key == key:
                return m
        return None


class Member:
    __slots__ = ("key", "key_start", "key_end", "value")

    def __init__(self, key, key_start, key_end, value):
        self.key, self.key_start, self.key_end, self.value = key, key_start, key_end, value


class Parser:
    def __init__(self, text):
        self.text, self.pos = text, 0

    def fail(self, message):
        raise ValueError(f"{message} at offset {self.pos}")

    def ws(self):
        t, n = self.text, len(self.text)
        while self.pos < n and t[self.pos] in " \t\r\n":
            self.pos += 1

    def parse(self):
        self.ws()
        node = self.value()
        self.ws()
        if self.pos != len(self.text):
            self.fail("trailing data")
        return node

    def value(self):
        self.ws()
        if self.pos >= len(self.text):
            self.fail("unexpected end")
        c = self.text[self.pos]
        if c == "{":
            return self.obj()
        if c == "[":
            return self.arr()
        if c == '"':
            start = self.pos
            s = self.string()
            node = Node("string", start)
            node.value, node.end = s, self.pos
            return node
        start = self.pos
        m = re.compile(r"-?(0|[1-9]\d*)(\.\d+)?([eE][+-]?\d+)?|true|false|null").match(self.text, self.pos)
        if not m:
            self.fail("invalid value")
        self.pos = m.end()
        node = Node("scalar", start)
        node.value, node.end = json.loads(m.group(0)), self.pos
        return node

    def string(self):
        start = self.pos
        self.pos += 1
        t = self.text
        while True:
            if self.pos >= len(t):
                self.fail("unterminated string")
            c = t[self.pos]
            if c == "\\":
                self.pos += 2
                continue
            self.pos += 1
            if c == '"':
                return json.loads(t[start:self.pos])

    def obj(self):
        node = Node("object", self.pos)
        self.pos += 1
        self.ws()
        if self.text[self.pos] == "}":
            self.pos += 1
            node.end = self.pos
            return node
        while True:
            self.ws()
            if self.text[self.pos] != '"':
                self.fail("expected key")
            key_start = self.pos
            key = self.string()
            key_end = self.pos
            self.ws()
            if self.text[self.pos] != ":":
                self.fail("expected ':'")
            self.pos += 1
            value = self.value()
            node.members.append(Member(key, key_start, key_end, value))
            self.ws()
            c = self.text[self.pos]
            self.pos += 1
            if c == "}":
                node.end = self.pos
                return node
            if c != ",":
                self.fail("expected ',' or '}'")

    def arr(self):
        node = Node("array", self.pos)
        self.pos += 1
        self.ws()
        if self.text[self.pos] == "]":
            self.pos += 1
            node.end = self.pos
            return node
        while True:
            node.items.append(self.value())
            self.ws()
            c = self.text[self.pos]
            self.pos += 1
            if c == "]":
                node.end = self.pos
                return node
            if c != ",":
                self.fail("expected ',' or ']'")


def locate(root, path):
    """Follows keys (str) and indices (int); returns the node or None."""
    node = root
    for step in path:
        if isinstance(step, int):
            if node.kind != "array" or step >= len(node.items):
                return None
            node = node.items[step]
        else:
            if node.kind != "object":
                return None
            m = node.member(step)
            if m is None:
                return None
            node = m.value
    return node


def format_kg(value):
    """Six significant digits, always written as a JSON float (0.0, 12.0, 0.185)."""
    text = f"{float(value):.6g}"
    if "e" in text or "E" in text:
        text = repr(float(value))
    elif "." not in text:
        text += ".0"
    return text


def same_number(a, b):
    return isinstance(a, (int, float)) and not isinstance(a, bool) and math.isclose(float(a), float(b), rel_tol=1e-9, abs_tol=1e-12)


def member_separator(text, obj):
    """(newline+indent before a member, key/value separator) as used by this object."""
    if obj.members:
        first = obj.members[0]
        lead = text[obj.start + 1:first.key_start]
        colon = text[first.key_end:first.value.start]
        if len(obj.members) > 1:
            second = obj.members[1]
            between = text[first.value.end:second.key_start]
            lead = between[between.index(",") + 1:] if "," in between else lead
        if "\n" not in lead:
            lead = " "  # inline object: one space after the comma
        return lead, colon
    return " ", ": "


def set_member(text, obj, key, value_text, after_keys=()):
    """Returns the new text with obj[key] = value_text (inserted after the first existing after_key, else last)."""
    existing = obj.member(key)
    if existing is not None:
        return text[:existing.value.start] + value_text + text[existing.value.end:]
    lead, colon = member_separator(text, obj)
    entry = f'"{key}"{colon}{value_text}'
    if not obj.members:
        closing = text[obj.start + 1:obj.end - 1]
        if "\n" in closing:
            indent = closing[closing.rindex("\n") + 1:]
            return text[:obj.start + 1] + "\n" + indent + "  " + entry + "\n" + indent + text[obj.end - 1:]
        return text[:obj.start + 1] + entry + text[obj.end - 1:]
    anchor = None
    for candidate in after_keys:
        anchor = obj.member(candidate)
        if anchor is not None:
            break
    if anchor is None:
        anchor = obj.members[-1]
    return text[:anchor.value.end] + "," + lead + entry + text[anchor.value.end:]


def remove_member(text, obj, key):
    index = next((i for i, m in enumerate(obj.members) if m.key == key), None)
    if index is None:
        return text
    member = obj.members[index]
    if len(obj.members) == 1:
        return text[:obj.start + 1] + text[obj.end - 1:]
    if index == 0:
        return text[:member.key_start] + text[obj.members[1].key_start:]
    previous = obj.members[index - 1]
    return text[:previous.value.end] + text[member.value.end:]


class JsonFile:
    def __init__(self, path):
        self.path = path
        with open(path, encoding="utf-8") as handle:
            self.original = handle.read()
        self.text = self.original
        self.root = Parser(self.text).parse()

    def reparse(self):
        self.root = Parser(self.text).parse()
        json.loads(self.text)  # the result must remain valid JSON

    def get(self, path, key):
        obj = locate(self.root, path)
        if obj is None or obj.kind != "object":
            return None, False
        m = obj.member(key)
        return (m.value.value if m is not None else None), m is not None

    def set(self, path, key, value, after_keys=()):
        """value None removes; returns 'written' | 'cleared' | 'unchanged' | 'missing-object'."""
        obj = locate(self.root, path)
        if obj is None or obj.kind != "object":
            return "missing-object"
        m = obj.member(key)
        if value is None:
            if m is None:
                return "unchanged"
            self.text = remove_member(self.text, obj, key)
            self.reparse()
            return "cleared"
        if m is not None and same_number(m.value.value, value):
            return "unchanged"
        self.text = set_member(self.text, obj, key, format_kg(value), after_keys)
        self.reparse()
        return "written"

    def add_override(self, path):
        """Adds an empty "Override" object to the dict entry at path; returns True when added."""
        obj = locate(self.root, path)
        if obj is None or obj.kind != "object" or obj.member("Override") is not None:
            return False
        self.text = set_member(self.text, obj, "Override", "{}")
        self.reparse()
        return True

    @property
    def changed(self):
        return self.text != self.original

    def save(self):
        with open(self.path, "w", encoding="utf-8", newline="") as handle:
            handle.write(self.text)


# --------------------------------------------------------------------------------------------------------------
# Row -> target resolution
# --------------------------------------------------------------------------------------------------------------
AFTER_WEAPON = ("ExplosionRadius", "ExplosionDamage")
AFTER_BOMB = ("BlastRadius", "BlastDamage")
AFTER_CLUSTER = ("BombletRadius", "BombletDamage")
AFTER_STORE = ("MassKg",)


class Target:
    __slots__ = ("file", "path", "key", "after", "kind", "base_path", "precedence", "row")

    def __init__(self, file, path, key, after, kind, row, base_path=None, precedence=0):
        self.file, self.path, self.key, self.after, self.kind = file, path, key, after, kind
        self.row, self.base_path, self.precedence = row, base_path, precedence

    @property
    def location(self):
        return (self.file, tuple(self.path), self.key)


def load_inventory(path):
    rows = OrderedDict()
    with open(path, encoding="utf-8") as handle:
        header = handle.readline().rstrip("\n").split("\t")
        for line in handle:
            if not line.strip():
                continue
            cells = line.rstrip("\n").split("\t")
            cells += [""] * (len(header) - len(cells))
            row = dict(zip(header, cells))
            rows[row["id"]] = row
    return rows


def resolve_target(row, repo, json_cache, warnings):
    """Returns (Target | None, skip_reason | None)."""
    rid, file = row["id"], row["file"]
    if rid.endswith("#destroy"):
        return None, "vehicle_destruction"
    if file.endswith(".kt") or file.endswith(".java"):
        return Target(DEFAULTS_PATH, ["entries"], rid, (), "defaults", rid), None
    m = ROW_SUFFIX.match(rid)
    head, list_name, index = m.group("head"), m.group("list"), m.group("index")
    if "/sbw/vehicles/" in file:
        weapon = head.split("/", 1)[1] if "/" in head else None
        if not weapon:
            raise ValueError(f"cannot parse weapon from {rid}")
        base = ["Weapons", weapon]
        if list_name:
            return Target(file, base + [list_name, int(index), "Override"], KEY, AFTER_WEAPON, "override", rid,
                          base_path=base), None
        return Target(file, base, KEY, AFTER_WEAPON, "weapon", rid), None
    if "/sbw/guns/" in file:
        if list_name:
            return Target(file, [list_name, int(index), "Override"], KEY, AFTER_WEAPON, "override", rid,
                          base_path=[]), None
        return Target(file, [], KEY, AFTER_WEAPON, "gun", rid), None
    if "/drone_attachments/" in file:
        return Target(file, [], KEY, AFTER_WEAPON, "drone", rid), None
    if "/aircraft_stores/" in file:
        if rid.endswith("#bomblet"):
            return Target(file, ["Bomb", "Cluster"], BOMBLET_KEY, AFTER_CLUSTER, "bomblet", rid), None
        store = json_cache(file)
        if "Bomb" in store:
            return Target(file, ["Bomb"], KEY, AFTER_BOMB, "bomb", rid), None
        if "Flight" in store:
            return Target(file, ["Flight"], KEY, AFTER_BOMB, "flight", rid), None
        gun = store.get("LaunchGunProfile") or store.get("GunProfile")
        if gun:
            ns, path = gun.split(":", 1)
            if ns != "berts_vehicle_pack":
                warnings.append(f"{rid}: gun profile {gun} is outside BVP; not written")
                return None, "external_gun_profile"
            gun_file = f"{BVP_GUNS}/{path}.json"
            if not os.path.exists(os.path.join(repo, gun_file)):
                warnings.append(f"{rid}: gun profile file {gun_file} not found")
                return None, "missing_gun_profile"
            # The store fires the gun profile's GunData; a direct guns/ row for the same file wins on conflict.
            return Target(gun_file, [], KEY, AFTER_WEAPON, "gun", rid, precedence=-1), None
        if "Guidance" in store:
            # FFA-launched store without a Flight block: SBW reads the store's top-level TntEquivalentKg.
            return Target(file, [], KEY, AFTER_STORE, "store", rid), None
        return None, "store_not_launchable"
    raise ValueError(f"{rid}: unrecognised data file {file}")


# --------------------------------------------------------------------------------------------------------------
def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    here = os.path.dirname(os.path.abspath(__file__))
    parser.add_argument("--table", default="/home/claude/tnt/tnt_table.json")
    parser.add_argument("--inventory", default="/home/claude/tnt/munition_inventory.tsv")
    parser.add_argument("--repo", default=os.path.normpath(os.path.join(here, "..", "..")))
    parser.add_argument("--dry-run", action="store_true", help="print the plan, write nothing")
    parser.add_argument("--verbose", "-v", action="store_true", help="list every change")
    args = parser.parse_args(argv)
    repo = os.path.abspath(args.repo)
    for label, path in (("table", args.table), ("inventory", args.inventory)):
        if not os.path.isfile(path):
            print(f"ERROR: {label} file not found: {path}")
            return 2

    with open(args.table, encoding="utf-8") as handle:
        table = json.load(handle)
    inventory = load_inventory(args.inventory)
    errors, warnings = [], []

    munitions = {}
    for entry in table.get("munitions", []):
        key, kg = entry.get("key"), entry.get("tnt_kg")
        if not isinstance(key, str) or not key:
            errors.append(f"munition without key: {entry}")
            continue
        if key in munitions:
            errors.append(f"duplicate munition key {key}")
        if kg is not None and (not isinstance(kg, (int, float)) or isinstance(kg, bool) or not math.isfinite(kg)
                               or kg < 0 or kg > MAX_KG):
            errors.append(f"munition {key}: invalid tnt_kg {kg!r}")
            continue
        munitions[key] = float(kg) if kg else 0.0
    mapping = table.get("rows", {})
    if not isinstance(mapping, dict):
        errors.append('"rows" must be an object')
        mapping = {}
    for rid, key in mapping.items():
        if rid not in inventory:
            errors.append(f"row {rid} is not in the inventory")
        elif key is not None and key not in munitions:
            errors.append(f"row {rid} maps to unknown munition {key}")

    json_cache_store = {}

    def load_json(rel):
        if rel not in json_cache_store:
            with open(os.path.join(repo, rel), encoding="utf-8") as handle:
                json_cache_store[rel] = json.load(handle)
        return json_cache_store[rel]

    # 1. Resolve every inventory row to a target and a desired value (None = clear, "unmapped" = leave base).
    counts = defaultdict(int)
    planned = {}  # location -> (Target, value)
    overrides_seen = defaultdict(set)  # (file, base path) -> {(list, index)} covered by rows
    for rid, row in inventory.items():
        try:
            target, skip = resolve_target(row, repo, load_json, warnings)
        except (ValueError, OSError, KeyError) as failure:
            errors.append(f"{rid}: {failure}")
            continue
        if target is None:
            counts[f"skipped_{skip}"] += 1
            if rid in mapping and mapping[rid] is not None and skip != "vehicle_destruction":
                warnings.append(f"{rid}: mapped to {mapping[rid]} but has no data target ({skip})")
            continue
        if target.kind == "override":
            m = ROW_SUFFIX.match(rid)
            overrides_seen[(target.file, tuple(target.base_path))].add((m.group("list"), int(m.group("index"))))
        if rid not in mapping:
            counts["unmapped"] += 1
            if target.kind != "override":
                continue
            value = None
        else:
            key = mapping[rid]
            value = munitions.get(key) if key is not None else None
            value = value if value else None
        location = target.location
        if location in planned:
            other, other_value = planned[location]
            if target.precedence < other.precedence:
                continue
            if target.precedence == other.precedence and other_value != value:
                errors.append(f"conflict at {location}: {other.row} -> {other_value}, {rid} -> {value}")
                continue
        planned[location] = (target, value)

    if errors:
        print("ERRORS (nothing written):")
        for message in errors:
            print("  " + message)
        return 2

    # 2. Apply base values first so overrides can be normalized against their final base.
    files = {}

    def open_file(rel):
        if rel not in files:
            files[rel] = JsonFile(os.path.join(repo, rel))
        return files[rel]

    changes = []
    defaults = OrderedDict()
    defaults_file = os.path.join(repo, DEFAULTS_PATH)
    with open(defaults_file, encoding="utf-8") as handle:
        defaults_doc = json.load(handle, object_pairs_hook=OrderedDict)
    defaults.update(defaults_doc.get("entries") or {})
    defaults_before = OrderedDict(defaults)

    def apply(target, value, reason=None):
        if target.kind == "defaults":
            if value is None:
                if target.key in defaults:
                    del defaults[target.key]
                    return "cleared"
                return "unchanged"
            if target.key in defaults and same_number(defaults[target.key], value):
                return "unchanged"
            defaults[target.key] = value
            return "written"
        return open_file(target.file).set(target.path, target.key, value, target.after)

    ordered = sorted(planned.values(), key=lambda item: item[0].kind == "override")
    for target, value in ordered:
        if target.kind == "override":
            continue
        result = apply(target, value)
        counts[result] += 1
        if result == "missing-object":
            warnings.append(f"{target.row}: object {'.'.join(map(str, target.path))} missing in {target.file}")
        elif result != "unchanged":
            changes.append(f"{result:9} {target.file} {'.'.join(map(str, target.path + [target.key]))} = {value}")

    def base_charge(rel, base_path):
        value, present = open_file(rel).get(base_path, KEY)
        return float(value) if present and isinstance(value, (int, float)) else 0.0

    for target, value in ordered:
        if target.kind != "override":
            continue
        charged_base = base_charge(target.file, target.base_path) > 0.0
        desired = value if value is not None else (0.0 if charged_base else None)
        document = open_file(target.file)
        entry_path = target.path[:-1]
        if locate(document.root, target.path) is None:
            if desired is None:
                counts["unchanged"] += 1
                continue
            if document.add_override(entry_path):
                counts["override_created"] += 1
        result = document.set(target.path, target.key, desired, target.after)
        if result == "missing-object":
            warnings.append(f"{target.row}: override object missing in {target.file}")
            continue
        counts[result if value is not None else ("override_zeroed" if desired == 0.0 and result == "written"
                                                   else result)] += 1
        if result != "unchanged":
            changes.append(f"{result:9} {target.file} {'.'.join(map(str, target.path + [target.key]))} = {desired}")

    # 3. AmmoType/belt entries without an inventory row inherit their base weapon's charge: force them to 0.
    # Only where the inventory enumerates overrides (vehicle weapons, SBW guns): there a missing override row
    # means a non-explosive ammo type. BVP gun profiles list only their base row, so their overrides inherit.
    def enumerates_overrides(rel):
        return "/sbw/vehicles/" in rel or rel.startswith("sbw/")

    bases = set()
    for target, _ in planned.values():
        if target.kind in ("weapon", "gun") and enumerates_overrides(target.file):
            bases.add((target.file, tuple(target.path)))
        if target.kind == "override" and enumerates_overrides(target.file):
            bases.add((target.file, tuple(target.base_path)))
    for rel, base in sorted(bases):
        document = open_file(rel)
        base_node = locate(document.root, list(base))
        if base_node is None or base_node.kind != "object":
            continue
        charged = base_charge(rel, list(base)) > 0.0
        for list_name in OVERRIDE_LISTS:
            list_node = locate(document.root, list(base) + [list_name])
            if list_node is None or list_node.kind != "array":
                continue
            for index, item in enumerate(list_node.items):
                if (list_name, index) in overrides_seen.get((rel, base), set()):
                    continue
                path = list(base) + [list_name, index, "Override"]
                # A string entry or a dict without "Override" uses the base weapon's values: that ammo *is* the
                # base munition (the inventory never lists it separately), so it keeps the base charge.
                if item.kind != "object" or item.member("Override") is None:
                    continue
                if charged:
                    result = document.set(path, KEY, 0.0, AFTER_WEAPON)
                    if result == "written":
                        counts["override_zeroed"] += 1
                        changes.append(f"zeroed    {rel} {'.'.join(map(str, path + [KEY]))} = 0")
                else:
                    result = document.set(path, KEY, None)
                    if result == "cleared":
                        counts["cleared"] += 1
                        changes.append(f"cleared   {rel} {'.'.join(map(str, path + [KEY]))}")

    defaults_changed = list(defaults.items()) != list(defaults_before.items())
    changed_files = sorted(rel for rel, document in files.items() if document.changed)
    if defaults_changed:
        changed_files.append(DEFAULTS_PATH)

    mode = "DRY RUN - nothing written" if args.dry_run else "applied"
    print(f"TNT-equivalent apply ({mode})")
    print(f"  table: {len(munitions)} munitions, {len(mapping)} row mappings "
          f"({sum(1 for v in mapping.values() if v is None)} null)")
    print(f"  inventory: {len(inventory)} rows; repo: {repo}")
    for name in sorted(counts):
        print(f"  {name}: {counts[name]}")
    print(f"  files changed: {len(changed_files)}")
    for rel in changed_files:
        print(f"    {rel}")
    if args.verbose:
        for line in changes:
            print("    " + line)
    if warnings:
        print(f"  warnings ({len(warnings)}):")
        for message in warnings:
            print("    " + message)

    if not args.dry_run:
        for rel in changed_files:
            if rel == DEFAULTS_PATH:
                continue
            files[rel].save()
        if defaults_changed:
            defaults_doc["entries"] = OrderedDict(sorted(defaults.items()))
            with open(defaults_file, "w", encoding="utf-8", newline="") as handle:
                handle.write(json.dumps(defaults_doc, indent=2, ensure_ascii=False) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
