package com.atsuishio.superbwarfare.client.flightdisplay

import com.atsuishio.superbwarfare.Mod
import com.atsuishio.superbwarfare.client.flightdisplay.GaugePainter.Kind
import com.atsuishio.superbwarfare.entity.vehicle.base.VehicleEntity
import com.atsuishio.superbwarfare.resource.vehicle.DefaultVehicleResource
import com.atsuishio.superbwarfare.resource.vehicle.VehicleResource
import com.mojang.blaze3d.pipeline.RenderTarget
import com.mojang.blaze3d.pipeline.TextureTarget
import com.mojang.blaze3d.platform.GlStateManager
import com.mojang.blaze3d.systems.RenderSystem
import com.mojang.blaze3d.vertex.PoseStack
import com.mojang.blaze3d.vertex.Tesselator
import com.mojang.blaze3d.vertex.VertexConsumer
import com.mojang.blaze3d.vertex.VertexSorting
import net.minecraft.client.Minecraft
import net.minecraft.client.gui.GuiGraphics
import net.minecraft.client.renderer.LightTexture
import net.minecraft.client.renderer.MultiBufferSource
import net.minecraft.client.renderer.RenderType
import net.minecraft.client.renderer.texture.AbstractTexture
import net.minecraft.client.renderer.texture.OverlayTexture
import net.minecraft.server.packs.resources.ResourceManager
import org.joml.Matrix4f
import org.joml.Vector3f
import org.lwjgl.opengl.GL11
import kotlin.math.cos
import kotlin.math.sin

/**
 * Round analogue ("steam") instruments for cockpits without electronic displays: altimeter, attitude indicator,
 * heading indicator and throttle work for the pilot of the aircraft the local player rides; other aircraft show
 * them at rest. Filler dials (fuel, oil, RPM, clock...) are fixed pictures.
 *
 * All faces live in one atlas texture of [GaugePainter.CELL]-texel cells: the live cells are repainted every frame
 * while the local player flies an aircraft with gauges, the rest once. Placement comes from the vehicle's client
 * resource ("CockpitGauges", generated by tools/cockpit_gauges/place.py).
 */
object CockpitGauges {
    private val LOGGER = Mod.LOGGER
    private val ATLAS = Mod.loc("dynamic/cockpit_gauges")
    private val CASE_TEXTURE = Mod.loc("textures/misc/flight_display_housing.png")
    private const val GRID = 5
    private const val SIZE = GaugePainter.CELL * GRID

    // Atlas cells: live kinds first, then still kinds, then fillers.
    private val LIVE = listOf(Kind.ALTIMETER, Kind.ATTITUDE, Kind.HEADING, Kind.THROTTLE)
    private val FILLERS = Kind.values().filter { !it.live }
    private fun liveCell(kind: Kind) = LIVE.indexOf(kind)
    private fun stillCell(kind: Kind) = if (kind.live) LIVE.size + LIVE.indexOf(kind) else 2 * LIVE.size + FILLERS.indexOf(kind)

    private var atlas: RenderTarget? = null
    private var staticPainted = false
    private var staticRequested = false
    private var liveVehicleId = -1
    private val liveKinds = HashSet<Kind>()
    private var failed = false
    private var logged = false

    /** Called from [FlightDisplays.onRenderTick] at the start of every frame, outside the world pass. */
    fun renderTick(partialTick: Float) {
        if (failed) return
        if (staticRequested && !staticPainted) {
            try {
                val target = atlas ?: create().also { atlas = it }
                paint(target, clear = true) { g ->
                    for (kind in Kind.values()) cell(g, stillCell(kind)) { GaugePainter.paint(g, kind, FlightDisplayState.STILL) }
                }
                staticPainted = true
                LOGGER.info("Cockpit gauge faces painted")
            } catch (e: Throwable) {
                failed = true
                LOGGER.error("Cockpit gauges failed; disabled for this session", e)
                return
            }
        }
        val mc = Minecraft.getInstance()
        val vehicle = mc.player?.vehicle as? VehicleEntity ?: run { liveVehicleId = -1; return }
        val gauges = gauges(vehicle) ?: run { liveVehicleId = -1; return }
        if (vehicle.isWreck || !staticPainted) { liveVehicleId = -1; return }
        val kinds = gauges.mapNotNull { Kind.of(it.kind) }.filter { it.live }.toSet()
        if (kinds.isEmpty()) { liveVehicleId = -1; return }
        val state = FlightDisplayState.sample(vehicle, partialTick) ?: return
        try {
            paint(atlas ?: return, clear = false) { g ->
                for (kind in kinds) cell(g, liveCell(kind)) { GaugePainter.paint(g, kind, state) }
            }
            liveKinds.clear(); liveKinds.addAll(kinds)
            liveVehicleId = vehicle.id
            if (!logged) {
                logged = true
                LOGGER.info("Live cockpit gauges active for {}: {}", VehicleResource.getDefault(vehicle).id, kinds)
            }
        } catch (e: Throwable) {
            failed = true
            LOGGER.error("Cockpit gauges failed; disabled for this session", e)
        }
    }

    private fun gauges(vehicle: VehicleEntity): Array<DefaultVehicleResource.CockpitGaugesResource.Gauge>? {
        val resource = VehicleResource.getDefault(vehicle).cockpitGauges ?: return null
        if (resource.frame != "VEHICLE_LOCAL_BLOCKS") return null
        return resource.gauges?.takeIf { it.isNotEmpty() }
    }

    /** Draws [vehicle]'s gauges in the vehicle model frame (see [FlightDisplays.render]). */
    fun render(vehicle: VehicleEntity, poseStack: PoseStack, buffers: MultiBufferSource, packedLight: Int) {
        if (failed) return
        val list = gauges(vehicle) ?: return
        if (!staticPainted) { staticRequested = true; return }
        val isLive = liveVehicleId == vehicle.id && Minecraft.getInstance().player?.vehicle === vehicle
        val pose = poseStack.last()
        val faces = buffers.getBuffer(RenderType.text(ATLAS))
        for (gauge in list) {
            val kind = Kind.of(gauge.kind) ?: continue
            val dial = Dial.of(gauge) ?: continue
            val cell = if (isLive && kind in liveKinds) liveCell(kind) else stillCell(kind)
            face(faces, pose.pose(), dial, cell)
        }
        val case = buffers.getBuffer(RenderType.entityCutoutNoCull(CASE_TEXTURE))
        for (gauge in list) {
            if (Kind.of(gauge.kind) == null) continue
            val dial = Dial.of(gauge) ?: continue
            case(case, pose, dial, packedLight)
        }
    }

    // ------------------------------------------------------------------ geometry

    private class Dial(val centre: Vector3f, val normal: Vector3f, val up: Vector3f, val right: Vector3f,
                       val radius: Float, val depth: Float) {
        fun point(x: Float, y: Float, back: Float): Vector3f = Vector3f(centre)
            .add(Vector3f(right).mul(x)).add(Vector3f(up).mul(y)).sub(Vector3f(normal).mul(back))

        companion object {
            fun of(d: DefaultVehicleResource.CockpitGaugesResource.Gauge): Dial? {
                val c = vec(d.center) ?: return null
                val n = vec(d.normal)?.takeIf { it.lengthSquared() > 1e-6f }?.normalize() ?: return null
                var u = vec(d.up) ?: return null
                u = u.sub(Vector3f(n).mul(u.dot(n))).takeIf { it.lengthSquared() > 1e-6f }?.normalize() ?: return null
                if (!(d.diameter > 0.01 && d.diameter < 0.5)) return null
                val r = Vector3f(u).cross(n).normalize()
                return Dial(c, n, u, r, (d.diameter / 2).toFloat(), d.depth.toFloat().coerceIn(0.004f, 0.1f))
            }

            private fun vec(a: DoubleArray?): Vector3f? = a?.takeIf { it.size == 3 && it.all(Double::isFinite) }
                ?.let { Vector3f(-it[0].toFloat(), it[1].toFloat(), -it[2].toFloat()) }
        }
    }

    private const val SEGMENTS = 32
    private const val RIM = 0.16f     // bezel ring width, fraction of the dial radius
    private const val PROUD = 0.006f  // bezel stands this far in front of the dial

    private fun face(consumer: VertexConsumer, matrix: Matrix4f, d: Dial, cell: Int) {
        val u0 = (cell % GRID).toFloat() / GRID; val v0 = (cell / GRID).toFloat() / GRID
        val du = 1f / GRID
        val r = d.radius
        val lift = 0.001f
        fun uv(x: Float, y: Float): FloatArray {
            // Render targets store their top row at v = 1; the cell's painted y grows downward.
            val cx = u0 + (x / r * 0.5f + 0.5f) * du
            val cy = 1f - (v0 + (0.5f - y / r * 0.5f) * du)
            return floatArrayOf(cx, cy)
        }
        for (k in 0 until SEGMENTS) {
            val a0 = k * 2 * Math.PI / SEGMENTS; val a1 = (k + 1) * 2 * Math.PI / SEGMENTS
            val x0 = (cos(a0) * r).toFloat(); val y0 = (sin(a0) * r).toFloat()
            val x1 = (cos(a1) * r).toFloat(); val y1 = (sin(a1) * r).toFloat()
            // A degenerate quad per segment (centre twice) keeps the QUADS vertex format of the text render type.
            for ((x, y) in arrayOf(0f to 0f, x0 to y0, x1 to y1, 0f to 0f)) {
                val p = d.point(x, y, -lift)
                val t = uv(x, y)
                consumer.vertex(matrix, p.x, p.y, p.z).color(236, 236, 230, 255).uv(t[0], t[1])
                    .uv2(LightTexture.FULL_BRIGHT).endVertex()
            }
        }
    }

    private fun case(consumer: VertexConsumer, pose: PoseStack.Pose, d: Dial, light: Int) {
        val r = d.radius
        val outer = r * (1f + RIM)
        for (k in 0 until SEGMENTS) {
            val a0 = k * 2 * Math.PI / SEGMENTS; val a1 = (k + 1) * 2 * Math.PI / SEGMENTS
            val c0 = cos(a0).toFloat(); val s0 = sin(a0).toFloat(); val c1 = cos(a1).toFloat(); val s1 = sin(a1).toFloat()
            // bezel ring front
            quad(consumer, pose, d.point(c0 * r, s0 * r, -PROUD), d.point(c0 * outer, s0 * outer, -PROUD),
                d.point(c1 * outer, s1 * outer, -PROUD), d.point(c1 * r, s1 * r, -PROUD), Vector3f(d.normal), light, 0.1f)
            // inner lip down to the dial
            val nIn = Vector3f(d.right).mul(-(c0 + c1) / 2).add(Vector3f(d.up).mul(-(s0 + s1) / 2))
            quad(consumer, pose, d.point(c0 * r, s0 * r, -PROUD), d.point(c1 * r, s1 * r, -PROUD),
                d.point(c1 * r, s1 * r, 0f), d.point(c0 * r, s0 * r, 0f), nIn, light, 0.06f)
            // outer wall back to the case depth
            val nOut = Vector3f(nIn).negate()
            quad(consumer, pose, d.point(c0 * outer, s0 * outer, -PROUD), d.point(c0 * outer, s0 * outer, d.depth),
                d.point(c1 * outer, s1 * outer, d.depth), d.point(c1 * outer, s1 * outer, -PROUD), nOut, light, 0.09f)
            // back
            quad(consumer, pose, d.point(0f, 0f, d.depth), d.point(c1 * outer, s1 * outer, d.depth),
                d.point(c0 * outer, s0 * outer, d.depth), d.point(0f, 0f, d.depth), Vector3f(d.normal).negate(), light, 0.08f)
        }
    }

    private fun quad(consumer: VertexConsumer, pose: PoseStack.Pose, a: Vector3f, b: Vector3f, c: Vector3f, e: Vector3f,
                     normal: Vector3f, light: Int, grey: Float) {
        val n = pose.normal().transform(Vector3f(normal).normalize())
        val uv = arrayOf(floatArrayOf(0f, 0f), floatArrayOf(0f, 1f), floatArrayOf(1f, 1f), floatArrayOf(1f, 0f))
        val g = (grey * 255 / 0.2f).toInt().coerceIn(0, 255)
        for ((i, p) in arrayOf(a, b, c, e).withIndex()) {
            consumer.vertex(pose.pose(), p.x, p.y, p.z).color(g, g, g, 255).uv(uv[i][0], uv[i][1])
                .overlayCoords(OverlayTexture.NO_OVERLAY).uv2(light).normal(n.x, n.y, n.z).endVertex()
        }
    }

    // ------------------------------------------------------------------ atlas painting

    private fun create(): RenderTarget {
        val target = TextureTarget(SIZE, SIZE, false, Minecraft.ON_OSX)
        target.setClearColor(0f, 0f, 0f, 1f)
        target.setFilterMode(GL11.GL_LINEAR)
        Minecraft.getInstance().textureManager.register(ATLAS, TargetTexture(target))
        return target
    }

    private inline fun cell(g: GuiGraphics, index: Int, body: () -> Unit) {
        val x = (index % GRID) * GaugePainter.CELL
        val y = (index / GRID) * GaugePainter.CELL
        // Clear the cell (live cells are repainted in place) and confine drawing to it.
        RenderSystem.enableScissor(x, SIZE - y - GaugePainter.CELL, GaugePainter.CELL, GaugePainter.CELL)
        g.pose().pushPose()
        g.pose().translate(x.toFloat(), y.toFloat(), 0f)
        g.fill(0, 0, GaugePainter.CELL, GaugePainter.CELL, 0xFF000000.toInt())
        body()
        g.flush()
        g.pose().popPose()
        RenderSystem.disableScissor()
    }

    private fun paint(target: RenderTarget, clear: Boolean, body: (GuiGraphics) -> Unit) {
        val mc = Minecraft.getInstance()
        RenderSystem.assertOnRenderThread()
        RenderSystem.backupProjectionMatrix()
        val modelView = RenderSystem.getModelViewStack()
        modelView.pushPose()
        val previousScissor = GL11.glIsEnabled(GL11.GL_SCISSOR_TEST)
        try {
            if (clear) target.clear(Minecraft.ON_OSX)
            target.bindWrite(true)
            RenderSystem.setProjectionMatrix(Matrix4f().setOrtho(0f, SIZE.toFloat(), SIZE.toFloat(), 0f, 1000f, 3000f),
                VertexSorting.ORTHOGRAPHIC_Z)
            modelView.setIdentity()
            modelView.translate(0f, 0f, -2000f)
            RenderSystem.applyModelViewMatrix()
            RenderSystem.disableDepthTest()
            RenderSystem.enableBlend()
            RenderSystem.defaultBlendFunc()
            val buffers = MultiBufferSource.immediate(Tesselator.getInstance().builder)
            val graphics = GuiGraphics(mc, buffers)
            body(graphics)
            graphics.flush()
        } finally {
            RenderSystem.disableScissor()
            if (previousScissor) GL11.glEnable(GL11.GL_SCISSOR_TEST)
            modelView.popPose()
            RenderSystem.applyModelViewMatrix()
            RenderSystem.restoreProjectionMatrix()
            RenderSystem.enableDepthTest()
            mc.mainRenderTarget.bindWrite(true)
        }
    }

    private class TargetTexture(private val target: RenderTarget) : AbstractTexture() {
        override fun getId(): Int = target.colorTextureId
        override fun load(manager: ResourceManager) {}
        override fun releaseId() {}
        override fun setFilter(blur: Boolean, mipmap: Boolean) {
            GlStateManager._bindTexture(getId())
            GlStateManager._texParameter(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MIN_FILTER, GL11.GL_LINEAR)
            GlStateManager._texParameter(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MAG_FILTER, GL11.GL_LINEAR)
        }
    }
}
