package com.atsuishio.superbwarfare.client.flightdisplay

import com.atsuishio.superbwarfare.Mod
import com.atsuishio.superbwarfare.entity.vehicle.base.VehicleEntity
import com.atsuishio.superbwarfare.resource.vehicle.DefaultVehicleResource
import com.atsuishio.superbwarfare.resource.vehicle.VehicleResource
import com.mojang.blaze3d.pipeline.RenderTarget
import com.mojang.blaze3d.pipeline.TextureTarget
import com.mojang.blaze3d.platform.GlStateManager
import com.mojang.blaze3d.systems.RenderSystem
import com.mojang.blaze3d.vertex.PoseStack
import com.mojang.blaze3d.vertex.Tesselator
import com.mojang.blaze3d.vertex.VertexConsumer
import com.mojang.blaze3d.vertex.VertexSorting
import net.minecraft.client.Minecraft
import net.minecraft.client.gui.GuiGraphics
import net.minecraft.client.renderer.LightTexture
import net.minecraft.client.renderer.MultiBufferSource
import net.minecraft.client.renderer.RenderType
import net.minecraft.client.renderer.texture.AbstractTexture
import net.minecraft.client.renderer.texture.OverlayTexture
import net.minecraft.resources.ResourceLocation
import net.minecraft.server.packs.resources.ResourceManager
import net.minecraftforge.api.distmarker.Dist
import net.minecraftforge.event.TickEvent
import net.minecraftforge.eventbus.api.SubscribeEvent
import org.joml.Matrix4f
import org.joml.Vector3f
import org.lwjgl.opengl.GL11

/**
 * Glass-cockpit electronic displays: primary flight display (PFD) and radar pages, on colour LCD or green CRT
 * screens, each in a multi-function display housing with push buttons around the bezel.
 *
 * The aircraft the local player rides shows live pages, redrawn every frame into off-screen textures before the world
 * renders. Every other aircraft shows a still picture of the same pages, drawn once. Screens are full-bright (their
 * own light, legible in any lighting); the housing behind them is lit like the cockpit.
 *
 * Placement comes from the vehicle's client resource ("FlightDisplays", generated by tools/flight_display/place.py
 * from each cockpit's geometry); aircraft without it (steam-gauge cockpits) get nothing here, see [CockpitGauges].
 */
@net.minecraftforge.fml.common.Mod.EventBusSubscriber(modid = Mod.MODID, value = [Dist.CLIENT])
object FlightDisplays {
    private val LOGGER = Mod.LOGGER
    private var loggedRender = 0
    private val HOUSING_TEXTURE = Mod.loc("textures/misc/flight_display_housing.png")
    private const val SUPERSAMPLE = 1
    private const val MAX_RENDER_DISTANCE_SQ = 96.0 * 96.0
    private const val BEZEL = 0.2           // housing border around the screen, fraction of the screen width
    private const val FACE = 0.006f         // housing front stands this far proud of the screen, blocks

    /** A page on a screen technology: one texture each, live and still. */
    private enum class Page(val radar: Boolean, val palette: DisplayPalette) {
        PFD_LCD(false, DisplayPalette.LCD), PFD_CRT(false, DisplayPalette.CRT),
        RADAR_LCD(true, DisplayPalette.LCD), RADAR_CRT(true, DisplayPalette.CRT);

        val liveTexture = Mod.loc("dynamic/flight_display_live_" + name.lowercase())
        val stillTexture = Mod.loc("dynamic/flight_display_still_" + name.lowercase())

        companion object {
            fun of(d: DefaultVehicleResource.FlightDisplaysResource.Display): Page {
                val radar = d.kind.equals("RADAR", ignoreCase = true)
                val crt = d.style.equals("CRT", ignoreCase = true)
                return if (radar) (if (crt) RADAR_CRT else RADAR_LCD) else (if (crt) PFD_CRT else PFD_LCD)
            }
        }
    }

    private val live = HashMap<Page, RenderTarget>()
    private val still = HashMap<Page, RenderTarget>()
    private val stillPainted = HashSet<Page>()
    private val stillRequested = HashSet<Page>()
    private val livePages = HashSet<Page>()
    private var liveVehicleId = -1
    private var failed = false
    private var loggedFirstLive = false
    private var paintsLogged = 0
    private var tickLogged = false

    /** Redraw the live pages for the aircraft the local player rides, before the world uses them this frame. */
    // No @JvmStatic: Kotlin-for-Forge registers this object instance, which only sees instance methods.
    @SubscribeEvent
    fun onRenderTick(event: TickEvent.RenderTickEvent) {
        if (event.phase != TickEvent.Phase.START || failed) return
        if (!tickLogged) { tickLogged = true; LOGGER.info("Flight displays: render tick hook active") }
        try {
            CockpitGauges.renderTick(event.renderTickTime)
        } catch (e: Throwable) {
            LOGGER.error("Cockpit gauges failed", e)
        }
        for (page in stillRequested.toList()) {
            if (page in stillPainted) continue
            try {
                val target = still.getOrPut(page) { create(page.stillTexture) }
                paint(target, page, FlightDisplayState.STILL, RadarDisplayState.STILL)
                stillPainted.add(page)
                LOGGER.info("Flight display still image painted: {}", page)
            } catch (e: Throwable) {
                failed = true
                LOGGER.error("Flight display still image failed; displays disabled for this session", e)
                return
            }
        }
        val mc = Minecraft.getInstance()
        val player = mc.player ?: return
        val vehicle = player.vehicle as? VehicleEntity ?: run { liveVehicleId = -1; return }
        val resource = displays(vehicle) ?: run { liveVehicleId = -1; return }
        if (resource.displays.isNullOrEmpty() || vehicle.isWreck) { liveVehicleId = -1; return }
        val state = FlightDisplayState.sample(vehicle, event.renderTickTime) ?: return
        val pages = resource.displays.map(Page::of).toSet()
        val radar = if (pages.any { it.radar }) RadarDisplayState.sample(vehicle, event.renderTickTime) else RadarDisplayState.STILL
        try {
            for (page in pages) paint(live.getOrPut(page) { create(page.liveTexture) }, page, state, radar)
            livePages.clear(); livePages.addAll(pages)
            liveVehicleId = vehicle.id
            if (!loggedFirstLive) {
                loggedFirstLive = true
                LOGGER.info("Live flight displays active for {}: {}", VehicleResource.getDefault(vehicle).id, pages)
            }
        } catch (e: Throwable) {
            failed = true
            LOGGER.error("Flight display rendering failed; displays disabled for this session", e)
        }
    }

    /**
     * Draws [vehicle]'s displays and gauges. [poseStack] is the vehicle model frame the BVP renderer draws the hull in:
     * vehicle local blocks rotated by 180 degrees about Y (model x = -left, z = -forward).
     */
    @JvmStatic
    fun render(vehicle: VehicleEntity, poseStack: PoseStack, buffers: MultiBufferSource, packedLight: Int) {
        if (vehicle.isWreck) return
        val mc = Minecraft.getInstance()
        val camera = mc.gameRenderer.mainCamera.position
        if (vehicle.position().distanceToSqr(camera) > MAX_RENDER_DISTANCE_SQ) return
        CockpitGauges.render(vehicle, poseStack, buffers, packedLight)
        if (failed) return
        val resource = displays(vehicle) ?: return
        val list = resource.displays ?: return
        if (list.isEmpty()) return
        val isLive = liveVehicleId == vehicle.id && mc.player?.vehicle === vehicle
        val pose = poseStack.last()
        for (display in list) {
            val quad = Quad.of(display) ?: continue
            val page = Page.of(display)
            // The still picture is painted at the start of the next frame, never in the middle of the world pass.
            val texture = if (isLive && page in livePages) page.liveTexture
                else if (page in stillPainted) page.stillTexture else { stillRequested.add(page); null }
            housing(buffers.getBuffer(RenderType.entityCutoutNoCull(HOUSING_TEXTURE)), pose, quad, packedLight)
            if (texture != null) screen(buffers.getBuffer(RenderType.text(texture)), pose.pose(), quad)
        }
        if (loggedRender < 4 && (loggedRender == 0 || isLive)) {
            loggedRender++
            LOGGER.info("Flight display drawn: vehicle {} live {} displays {} poseDet {}",
                VehicleResource.getDefault(vehicle).id, isLive, list.size, pose.pose().determinant())
        }
    }

    private fun displays(vehicle: VehicleEntity): DefaultVehicleResource.FlightDisplaysResource? {
        val resource = VehicleResource.getDefault(vehicle).flightDisplays ?: return null
        return resource.takeIf { it.frame == "VEHICLE_LOCAL_BLOCKS" }
    }

    // ------------------------------------------------------------------ geometry

    /** Screen corners and basis in the model frame (vehicle local blocks turned 180 degrees about Y). */
    private class Quad(val centre: Vector3f, val normal: Vector3f, val up: Vector3f, val right: Vector3f,
                       val half: Float, val depth: Float) {
        fun point(sx: Float, sy: Float, back: Float): Vector3f = Vector3f(centre)
            .add(Vector3f(right).mul(sx)).add(Vector3f(up).mul(sy)).sub(Vector3f(normal).mul(back))

        companion object {
            fun of(d: DefaultVehicleResource.FlightDisplaysResource.Display): Quad? {
                val c = vec(d.center) ?: return null
                val n = vec(d.normal)?.takeIf { it.lengthSquared() > 1e-6f }?.normalize() ?: return null
                var u = vec(d.up) ?: return null
                u = u.sub(Vector3f(n).mul(u.dot(n))).takeIf { it.lengthSquared() > 1e-6f }?.normalize() ?: return null
                if (!(d.width > 0.01 && d.width < 2.0)) return null
                // From the crew member's side (normal toward them), screen right = up x normal.
                val r = Vector3f(u).cross(n).normalize()
                return Quad(c, n, u, r, (d.width / 2).toFloat(), d.depth.toFloat().coerceIn(0.005f, 0.2f))
            }

            /** Vehicle-local (+X left, +Z forward) to the model frame: rotate 180 degrees about Y. */
            private fun vec(a: DoubleArray?): Vector3f? = a?.takeIf { it.size == 3 && it.all(Double::isFinite) }
                ?.let { Vector3f(-it[0].toFloat(), it[1].toFloat(), -it[2].toFloat()) }
        }
    }

    private fun screen(consumer: VertexConsumer, matrix: Matrix4f, q: Quad) {
        val lift = 0.0015f
        val h = q.half
        // Render targets store their top row at v = 1.
        val corners = arrayOf(
            floatArrayOf(-h, h, 0f, 1f), floatArrayOf(-h, -h, 0f, 0f),
            floatArrayOf(h, -h, 1f, 0f), floatArrayOf(h, h, 1f, 1f))
        for (c in corners) emit(consumer, matrix, q, c, lift)
        // Also the reverse winding (faces into the housing, hidden), so no cull setting can lose the screen.
        for (c in corners.reversedArray()) emit(consumer, matrix, q, c, lift)
    }

    private fun emit(consumer: VertexConsumer, matrix: Matrix4f, q: Quad, c: FloatArray, lift: Float) {
        val p = q.point(c[0], c[1], -lift)
        consumer.vertex(matrix, p.x, p.y, p.z).color(255, 255, 255, 255).uv(c[2], c[3])
            .uv2(LightTexture.FULL_BRIGHT).endVertex()
    }

    private fun housing(consumer: VertexConsumer, pose: PoseStack.Pose, q: Quad, light: Int) {
        val h = q.half
        val o = h * (1f + 2f * BEZEL.toFloat())
        val d = q.depth
        // Case behind the screen plane, then the raised bezel frame around the screen opening.
        box(consumer, pose, q, -o, -o, o, o, 0f, d, light, 0.12f)
        frame(consumer, pose, q, h, o, light)
        // Push buttons: 5 along the top and bottom, 6 down each side, centred in the bezel strips and lined up with
        // the page legends; rocker switches in the corners.
        val strip = (o + h) / 2
        val bw = h * 0.16f; val bh = h * 0.1f; val proud = FACE + 0.004f
        for (k in 0 until 5) {
            val x = -h + 2 * h * (k + 1) / 6f
            box(consumer, pose, q, x - bw / 2, strip - bh / 2, x + bw / 2, strip + bh / 2, -proud, -FACE, light, 0.2f)
            box(consumer, pose, q, x - bw / 2, -strip - bh / 2, x + bw / 2, -strip + bh / 2, -proud, -FACE, light, 0.2f)
        }
        for (k in 0 until 6) {
            val y = h - 2 * h * (k + 1) / 7f
            box(consumer, pose, q, strip - bh / 2, y - bw / 2, strip + bh / 2, y + bw / 2, -proud, -FACE, light, 0.2f)
            box(consumer, pose, q, -strip - bh / 2, y - bw / 2, -strip + bh / 2, y + bw / 2, -proud, -FACE, light, 0.2f)
        }
        val rk = h * 0.09f
        for (sx in floatArrayOf(-1f, 1f)) for (sy in floatArrayOf(-1f, 1f)) {
            val cx = sx * strip; val cy = sy * strip
            box(consumer, pose, q, cx - rk, cy - rk * 1.6f, cx + rk, cy + rk * 1.6f, -proud - 0.002f, -FACE, light, 0.17f)
        }
    }

    /** Bezel frame: front face around the screen opening, and the well down to the screen. */
    private fun frame(consumer: VertexConsumer, pose: PoseStack.Pose, q: Quad, h: Float, o: Float, light: Int) {
        val f = -FACE
        val n = Vector3f(q.normal)
        // front, four strips (screen-local x right, y up)
        rect(consumer, pose, q, -o, h, o, o, f, n, light, 0.13f)
        rect(consumer, pose, q, -o, -o, o, -h, f, n, light, 0.13f)
        rect(consumer, pose, q, -o, -h, -h, h, f, n, light, 0.13f)
        rect(consumer, pose, q, h, -h, o, h, f, n, light, 0.13f)
        // outer sides from the face back to the case
        box(consumer, pose, q, -o, -o, o, o, f, 0f, light, 0.12f, frontFace = false)
        // well walls, facing into the opening
        quad(consumer, pose, q.point(-h, h, f), q.point(h, h, f), q.point(h, h, 0f), q.point(-h, h, 0f),
            Vector3f(q.up).negate(), light, 0.08f)
        quad(consumer, pose, q.point(-h, -h, 0f), q.point(h, -h, 0f), q.point(h, -h, f), q.point(-h, -h, f),
            Vector3f(q.up), light, 0.08f)
        quad(consumer, pose, q.point(-h, -h, f), q.point(-h, h, f), q.point(-h, h, 0f), q.point(-h, -h, 0f),
            Vector3f(q.right), light, 0.08f)
        quad(consumer, pose, q.point(h, -h, 0f), q.point(h, h, 0f), q.point(h, h, f), q.point(h, -h, f),
            Vector3f(q.right).negate(), light, 0.08f)
    }

    private fun rect(consumer: VertexConsumer, pose: PoseStack.Pose, q: Quad, x0: Float, y0: Float, x1: Float, y1: Float,
                     back: Float, n: Vector3f, light: Int, grey: Float) {
        quad(consumer, pose, q.point(x0, y1, back), q.point(x0, y0, back), q.point(x1, y0, back), q.point(x1, y1, back),
            n, light, grey)
    }

    /** Box in screen-local coordinates: x0..x1 right, y0..y1 up, front..back behind the screen plane. */
    private fun box(consumer: VertexConsumer, pose: PoseStack.Pose, q: Quad, x0: Float, y0: Float, x1: Float, y1: Float,
                    front: Float, back: Float, light: Int, grey: Float, frontFace: Boolean = true) {
        val f = arrayOf(q.point(x0, y1, front), q.point(x1, y1, front), q.point(x1, y0, front), q.point(x0, y0, front))
        val b = arrayOf(q.point(x0, y1, back), q.point(x1, y1, back), q.point(x1, y0, back), q.point(x0, y0, back))
        if (frontFace) quad(consumer, pose, f[0], f[3], f[2], f[1], Vector3f(q.normal), light, grey)
        quad(consumer, pose, b[0], b[1], b[2], b[3], Vector3f(q.normal).negate(), light, grey * 0.8f)
        quad(consumer, pose, f[0], f[1], b[1], b[0], Vector3f(q.up), light, grey)
        quad(consumer, pose, f[3], b[3], b[2], f[2], Vector3f(q.up).negate(), light, grey * 0.85f)
        quad(consumer, pose, f[1], f[2], b[2], b[1], Vector3f(q.right), light, grey * 0.9f)
        quad(consumer, pose, f[0], b[0], b[3], f[3], Vector3f(q.right).negate(), light, grey * 0.9f)
    }

    private fun quad(consumer: VertexConsumer, pose: PoseStack.Pose, a: Vector3f, b: Vector3f, c: Vector3f, d: Vector3f,
                     normal: Vector3f, light: Int, grey: Float) {
        val n = pose.normal().transform(Vector3f(normal))
        val uv = arrayOf(floatArrayOf(0f, 0f), floatArrayOf(0f, 1f), floatArrayOf(1f, 1f), floatArrayOf(1f, 0f))
        val g = (grey * 255 / 0.2f).toInt().coerceIn(0, 255)
        for ((i, p) in arrayOf(a, b, c, d).withIndex()) {
            consumer.vertex(pose.pose(), p.x, p.y, p.z).color(g, g, g, 255).uv(uv[i][0], uv[i][1])
                .overlayCoords(OverlayTexture.NO_OVERLAY).uv2(light).normal(n.x, n.y, n.z).endVertex()
        }
    }

    // ------------------------------------------------------------------ off-screen painting

    private fun create(location: ResourceLocation): RenderTarget {
        val size = PrimaryFlightDisplayPainter.SIZE * SUPERSAMPLE
        val target = TextureTarget(size, size, false, Minecraft.ON_OSX)
        target.setClearColor(0f, 0f, 0f, 1f)
        target.setFilterMode(GL11.GL_LINEAR)
        Minecraft.getInstance().textureManager.register(location, TargetTexture(target))
        return target
    }

    /** Runs at the start of a frame, outside the world pass; still saves and restores the state it touches. */
    private fun paint(target: RenderTarget, page: Page, state: FlightDisplayState, radar: RadarDisplayState) {
        val mc = Minecraft.getInstance()
        RenderSystem.assertOnRenderThread()
        val size = PrimaryFlightDisplayPainter.SIZE.toFloat()
        RenderSystem.backupProjectionMatrix()
        val modelView = RenderSystem.getModelViewStack()
        modelView.pushPose()
        val previousScissor = GL11.glIsEnabled(GL11.GL_SCISSOR_TEST)
        try {
            target.clear(Minecraft.ON_OSX)
            target.bindWrite(true)
            RenderSystem.setProjectionMatrix(Matrix4f().setOrtho(0f, size, size, 0f, 1000f, 3000f), VertexSorting.ORTHOGRAPHIC_Z)
            modelView.setIdentity()
            modelView.translate(0f, 0f, -2000f)
            RenderSystem.applyModelViewMatrix()
            RenderSystem.disableDepthTest()
            RenderSystem.enableBlend()
            RenderSystem.defaultBlendFunc()
            val buffers = MultiBufferSource.immediate(Tesselator.getInstance().builder)
            val graphics = GuiGraphics(mc, buffers)
            if (SUPERSAMPLE != 1) graphics.pose().scale(SUPERSAMPLE.toFloat(), SUPERSAMPLE.toFloat(), 1f)
            if (page.radar) RadarDisplayPainter.paint(graphics, radar, SUPERSAMPLE, page.palette)
            else PrimaryFlightDisplayPainter.paint(graphics, state, SUPERSAMPLE, page.palette)
            graphics.flush()
            if (paintsLogged < 3) {
                paintsLogged++
                val px = org.lwjgl.BufferUtils.createByteBuffer(4)
                GL11.glReadPixels(PrimaryFlightDisplayPainter.SIZE / 2, PrimaryFlightDisplayPainter.SIZE * 3 / 4, 1, 1,
                    GL11.GL_RGBA, GL11.GL_UNSIGNED_BYTE, px)
                LOGGER.info("Flight display painted: texture id {} centre-top pixel rgba {} {} {} {}", target.colorTextureId,
                    px.get(0).toInt() and 255, px.get(1).toInt() and 255, px.get(2).toInt() and 255, px.get(3).toInt() and 255)
            }
        } finally {
            RenderSystem.disableScissor()
            if (previousScissor) GL11.glEnable(GL11.GL_SCISSOR_TEST)
            modelView.popPose()
            RenderSystem.applyModelViewMatrix()
            RenderSystem.restoreProjectionMatrix()
            RenderSystem.enableDepthTest()
            mc.mainRenderTarget.bindWrite(true)
        }
    }

    /** Exposes a render target's colour attachment to render types, always linearly filtered. */
    private class TargetTexture(private val target: RenderTarget) : AbstractTexture() {
        override fun getId(): Int = target.colorTextureId
        override fun load(manager: ResourceManager) {}
        override fun releaseId() {}
        override fun setFilter(blur: Boolean, mipmap: Boolean) {
            GlStateManager._bindTexture(getId())
            GlStateManager._texParameter(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MIN_FILTER, GL11.GL_LINEAR)
            GlStateManager._texParameter(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MAG_FILTER, GL11.GL_LINEAR)
        }
    }
}
