package com.atsuishio.superbwarfare.client.flightdisplay

import com.atsuishio.superbwarfare.Mod
import com.atsuishio.superbwarfare.entity.vehicle.base.VehicleEntity
import com.atsuishio.superbwarfare.resource.vehicle.DefaultVehicleResource
import com.atsuishio.superbwarfare.resource.vehicle.VehicleResource
import com.mojang.blaze3d.pipeline.RenderTarget
import com.mojang.blaze3d.pipeline.TextureTarget
import com.mojang.blaze3d.platform.GlStateManager
import com.mojang.blaze3d.systems.RenderSystem
import com.mojang.blaze3d.vertex.PoseStack
import com.mojang.blaze3d.vertex.Tesselator
import com.mojang.blaze3d.vertex.VertexConsumer
import com.mojang.blaze3d.vertex.VertexSorting
import net.minecraft.client.Minecraft
import net.minecraft.client.gui.GuiGraphics
import net.minecraft.client.renderer.LightTexture
import net.minecraft.client.renderer.MultiBufferSource
import net.minecraft.client.renderer.RenderType
import net.minecraft.client.renderer.texture.AbstractTexture
import net.minecraft.client.renderer.texture.OverlayTexture
import net.minecraft.resources.ResourceLocation
import net.minecraft.server.packs.resources.ResourceManager
import net.minecraftforge.api.distmarker.Dist
import net.minecraftforge.event.TickEvent
import net.minecraftforge.eventbus.api.SubscribeEvent
import org.joml.Matrix4f
import org.joml.Vector3f
import org.lwjgl.opengl.GL11

/**
 * Glass-cockpit primary flight displays.
 *
 * The aircraft the local player rides shows a live display, redrawn every frame into an off-screen texture before
 * the world renders. Every other aircraft shows a still picture of the same display, drawn once. Screens are
 * full-bright (their own light, legible in any lighting); the housing behind them is lit like the cockpit.
 *
 * Placement comes from the vehicle's client resource ("FlightDisplays", generated by tools/flight_display/place.py
 * from each cockpit's geometry); aircraft without it (steam-gauge cockpits) get nothing.
 */
@net.minecraftforge.fml.common.Mod.EventBusSubscriber(modid = Mod.MODID, value = [Dist.CLIENT])
object FlightDisplays {
    private val LOGGER = Mod.LOGGER
    private var loggedRender = 0
    private val LIVE_TEXTURE = Mod.loc("dynamic/flight_display_live")
    private val STILL_TEXTURE = Mod.loc("dynamic/flight_display_still")
    private val HOUSING_TEXTURE = Mod.loc("textures/misc/flight_display_housing.png")
    private const val SUPERSAMPLE = 1
    private const val MAX_RENDER_DISTANCE_SQ = 96.0 * 96.0
    private const val BEZEL = 0.07          // housing border around the screen, fraction of the screen width

    private var live: RenderTarget? = null
    private var still: RenderTarget? = null
    private var stillPainted = false
    private var stillRequested = false
    private var liveVehicleId = -1
    private var failed = false
    private var loggedFirstLive = false
    private var paintsLogged = 0
    private var tickLogged = false

    /** Redraw the live display for the aircraft the local player rides, before the world uses it this frame. */
    // No @JvmStatic: Kotlin-for-Forge registers this object instance, which only sees instance methods.
    @SubscribeEvent
    fun onRenderTick(event: TickEvent.RenderTickEvent) {
        if (event.phase != TickEvent.Phase.START || failed) return
        if (!tickLogged) { tickLogged = true; LOGGER.info("Flight displays: render tick hook active") }
        if (stillRequested && !stillPainted) {
            try {
                val target = still ?: create(STILL_TEXTURE).also { still = it }
                paint(target, FlightDisplayState.STILL)
                stillPainted = true
                LOGGER.info("Primary flight display still image painted")
            } catch (e: Throwable) {
                failed = true
                LOGGER.error("Primary flight display still image failed; displays disabled for this session", e)
                return
            }
        }
        val mc = Minecraft.getInstance()
        val player = mc.player ?: return
        val vehicle = player.vehicle as? VehicleEntity ?: run { liveVehicleId = -1; return }
        val resource = displays(vehicle) ?: run { liveVehicleId = -1; return }
        if (resource.displays.isNullOrEmpty() || vehicle.isWreck) { liveVehicleId = -1; return }
        val state = FlightDisplayState.sample(vehicle, event.renderTickTime) ?: return
        try {
            val target = live ?: create(LIVE_TEXTURE).also { live = it }
            paint(target, state)
            liveVehicleId = vehicle.id
            if (!loggedFirstLive) {
                loggedFirstLive = true
                LOGGER.info("Live primary flight display active for {} ({} display(s))",
                    VehicleResource.getDefault(vehicle).id, resource.displays.size)
            }
        } catch (e: Throwable) {
            failed = true
            LOGGER.error("Primary flight display rendering failed; displays disabled for this session", e)
        }
    }

    /**
     * Draws [vehicle]'s displays. [poseStack] is the vehicle model frame the BVP renderer draws the hull in: vehicle
     * local blocks rotated by 180 degrees about Y (model x = -left, z = -forward).
     */
    @JvmStatic
    fun render(vehicle: VehicleEntity, poseStack: PoseStack, buffers: MultiBufferSource, packedLight: Int) {
        if (failed || vehicle.isWreck) return
        val resource = displays(vehicle) ?: return
        val list = resource.displays ?: return
        if (list.isEmpty()) return
        val mc = Minecraft.getInstance()
        val camera = mc.gameRenderer.mainCamera.position
        if (vehicle.position().distanceToSqr(camera) > MAX_RENDER_DISTANCE_SQ) return
        val isLive = liveVehicleId == vehicle.id && mc.player?.vehicle === vehicle
        // The still picture is painted at the start of the next frame, never in the middle of the world pass.
        val texture = if (isLive) LIVE_TEXTURE else if (stillPainted) STILL_TEXTURE else { stillRequested = true; null }
        val pose = poseStack.last()
        for (display in list) {
            val quad = Quad.of(display) ?: continue
            housing(buffers.getBuffer(RenderType.entityCutoutNoCull(HOUSING_TEXTURE)), pose, quad, packedLight)
            if (texture != null) screen(buffers.getBuffer(RenderType.text(texture)), pose.pose(), quad)
        }
        if (loggedRender < 4 && (loggedRender == 0 || isLive)) {
            loggedRender++
            LOGGER.info("Flight display drawn: vehicle {} live {} texture {} displays {} poseDet {}",
                VehicleResource.getDefault(vehicle).id, isLive, texture, list.size, pose.pose().determinant())
        }
    }

    private fun displays(vehicle: VehicleEntity): DefaultVehicleResource.FlightDisplaysResource? {
        val resource = VehicleResource.getDefault(vehicle).flightDisplays ?: return null
        return resource.takeIf { it.frame == "VEHICLE_LOCAL_BLOCKS" }
    }

    // ------------------------------------------------------------------ geometry

    /** Screen corners and basis in the model frame (vehicle local blocks turned 180 degrees about Y). */
    private class Quad(val centre: Vector3f, val normal: Vector3f, val up: Vector3f, val right: Vector3f,
                       val half: Float, val depth: Float) {
        fun point(sx: Float, sy: Float, back: Float): Vector3f = Vector3f(centre)
            .add(Vector3f(right).mul(sx)).add(Vector3f(up).mul(sy)).sub(Vector3f(normal).mul(back))

        companion object {
            fun of(d: DefaultVehicleResource.FlightDisplaysResource.Display): Quad? {
                val c = vec(d.center) ?: return null
                val n = vec(d.normal)?.takeIf { it.lengthSquared() > 1e-6f }?.normalize() ?: return null
                var u = vec(d.up) ?: return null
                u = u.sub(Vector3f(n).mul(u.dot(n))).takeIf { it.lengthSquared() > 1e-6f }?.normalize() ?: return null
                if (!(d.width > 0.01 && d.width < 2.0)) return null
                // From the crew member's side (normal toward them), screen right = up x normal.
                val r = Vector3f(u).cross(n).normalize()
                return Quad(c, n, u, r, (d.width / 2).toFloat(), d.depth.toFloat().coerceIn(0.005f, 0.2f))
            }

            /** Vehicle-local (+X left, +Z forward) to the model frame: rotate 180 degrees about Y. */
            private fun vec(a: DoubleArray?): Vector3f? = a?.takeIf { it.size == 3 && it.all(Double::isFinite) }
                ?.let { Vector3f(-it[0].toFloat(), it[1].toFloat(), -it[2].toFloat()) }
        }
    }

    private fun screen(consumer: VertexConsumer, matrix: Matrix4f, q: Quad) {
        val lift = 0.0015f
        val h = q.half
        // Render targets store their top row at v = 1.
        val corners = arrayOf(
            floatArrayOf(-h, h, 0f, 1f), floatArrayOf(-h, -h, 0f, 0f),
            floatArrayOf(h, -h, 1f, 0f), floatArrayOf(h, h, 1f, 1f))
        for (c in corners) emit(consumer, matrix, q, c, lift)
        // Also the reverse winding (faces into the housing, hidden), so no cull setting can lose the screen.
        for (c in corners.reversedArray()) emit(consumer, matrix, q, c, lift)
    }

    private fun emit(consumer: VertexConsumer, matrix: Matrix4f, q: Quad, c: FloatArray, lift: Float) {
        val p = q.point(c[0], c[1], -lift)
        consumer.vertex(matrix, p.x, p.y, p.z).color(255, 255, 255, 255).uv(c[2], c[3])
            .uv2(LightTexture.FULL_BRIGHT).endVertex()
    }

    private fun housing(consumer: VertexConsumer, pose: PoseStack.Pose, q: Quad, light: Int) {
        val o = q.half * (1f + 2f * BEZEL.toFloat())
        val d = q.depth
        val face = 0.0005f
        // front frame (behind the screen), four sides, back
        box(consumer, pose, q, o, face, d, light)
    }

    private fun box(consumer: VertexConsumer, pose: PoseStack.Pose, q: Quad, o: Float, front: Float, back: Float, light: Int) {
        val f = arrayOf(q.point(-o, o, -front), q.point(o, o, -front), q.point(o, -o, -front), q.point(-o, -o, -front))
        val b = arrayOf(q.point(-o, o, back), q.point(o, o, back), q.point(o, -o, back), q.point(-o, -o, back))
        val nFront = Vector3f(q.normal)
        quad(consumer, pose, f[0], f[3], f[2], f[1], nFront, light, 0.16f)
        quad(consumer, pose, b[0], b[1], b[2], b[3], Vector3f(q.normal).negate(), light, 0.12f)
        quad(consumer, pose, f[0], f[1], b[1], b[0], Vector3f(q.up), light, 0.2f)
        quad(consumer, pose, f[3], b[3], b[2], f[2], Vector3f(q.up).negate(), light, 0.2f)
        quad(consumer, pose, f[1], f[2], b[2], b[1], Vector3f(q.right), light, 0.2f)
        quad(consumer, pose, f[0], b[0], b[3], f[3], Vector3f(q.right).negate(), light, 0.2f)
    }

    private fun quad(consumer: VertexConsumer, pose: PoseStack.Pose, a: Vector3f, b: Vector3f, c: Vector3f, d: Vector3f,
                     normal: Vector3f, light: Int, grey: Float) {
        val n = pose.normal().transform(Vector3f(normal))
        val uv = arrayOf(floatArrayOf(0f, 0f), floatArrayOf(0f, 1f), floatArrayOf(1f, 1f), floatArrayOf(1f, 0f))
        val g = (grey * 255 / 0.2f).toInt().coerceIn(0, 255)
        for ((i, p) in arrayOf(a, b, c, d).withIndex()) {
            consumer.vertex(pose.pose(), p.x, p.y, p.z).color(g, g, g, 255).uv(uv[i][0], uv[i][1])
                .overlayCoords(OverlayTexture.NO_OVERLAY).uv2(light).normal(n.x, n.y, n.z).endVertex()
        }
    }

    // ------------------------------------------------------------------ off-screen painting

    private fun create(location: ResourceLocation): RenderTarget {
        val size = PrimaryFlightDisplayPainter.SIZE * SUPERSAMPLE
        val target = TextureTarget(size, size, false, Minecraft.ON_OSX)
        target.setClearColor(0f, 0f, 0f, 1f)
        target.setFilterMode(GL11.GL_LINEAR)
        Minecraft.getInstance().textureManager.register(location, TargetTexture(target))
        return target
    }

    /** Runs at the start of a frame, outside the world pass; still saves and restores the state it touches. */
    private fun paint(target: RenderTarget, state: FlightDisplayState) {
        val mc = Minecraft.getInstance()
        RenderSystem.assertOnRenderThread()
        val size = PrimaryFlightDisplayPainter.SIZE.toFloat()
        RenderSystem.backupProjectionMatrix()
        val modelView = RenderSystem.getModelViewStack()
        modelView.pushPose()
        val previousScissor = GL11.glIsEnabled(GL11.GL_SCISSOR_TEST)
        try {
            target.clear(Minecraft.ON_OSX)
            target.bindWrite(true)
            RenderSystem.setProjectionMatrix(Matrix4f().setOrtho(0f, size, size, 0f, 1000f, 3000f), VertexSorting.ORTHOGRAPHIC_Z)
            modelView.setIdentity()
            modelView.translate(0f, 0f, -2000f)
            RenderSystem.applyModelViewMatrix()
            RenderSystem.disableDepthTest()
            RenderSystem.enableBlend()
            RenderSystem.defaultBlendFunc()
            val buffers = MultiBufferSource.immediate(Tesselator.getInstance().builder)
            val graphics = GuiGraphics(mc, buffers)
            if (SUPERSAMPLE != 1) graphics.pose().scale(SUPERSAMPLE.toFloat(), SUPERSAMPLE.toFloat(), 1f)
            PrimaryFlightDisplayPainter.paint(graphics, state, SUPERSAMPLE)
            graphics.flush()
            if (paintsLogged < 3) {
                paintsLogged++
                val px = org.lwjgl.BufferUtils.createByteBuffer(4)
                GL11.glReadPixels(PrimaryFlightDisplayPainter.SIZE / 2, PrimaryFlightDisplayPainter.SIZE * 3 / 4, 1, 1,
                    GL11.GL_RGBA, GL11.GL_UNSIGNED_BYTE, px)
                LOGGER.info("Flight display painted: texture id {} centre-top pixel rgba {} {} {} {}", target.colorTextureId,
                    px.get(0).toInt() and 255, px.get(1).toInt() and 255, px.get(2).toInt() and 255, px.get(3).toInt() and 255)
            }
        } finally {
            RenderSystem.disableScissor()
            if (previousScissor) GL11.glEnable(GL11.GL_SCISSOR_TEST)
            modelView.popPose()
            RenderSystem.applyModelViewMatrix()
            RenderSystem.restoreProjectionMatrix()
            RenderSystem.enableDepthTest()
            mc.mainRenderTarget.bindWrite(true)
        }
    }

    /** Exposes a render target's colour attachment to render types, always linearly filtered. */
    private class TargetTexture(private val target: RenderTarget) : AbstractTexture() {
        override fun getId(): Int = target.colorTextureId
        override fun load(manager: ResourceManager) {}
        override fun releaseId() {}
        override fun setFilter(blur: Boolean, mipmap: Boolean) {
            GlStateManager._bindTexture(getId())
            GlStateManager._texParameter(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MIN_FILTER, GL11.GL_LINEAR)
            GlStateManager._texParameter(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MAG_FILTER, GL11.GL_LINEAR)
        }
    }
}
